<!-- Átlátszónet aloldala: Képzések, workshopok-->
<div class="container">
	<div class="row">
	<!--Bal rész, fő szöveg-->
		<div class="col-sm-8 text-justify">
			<h1><u>Képzések, workshopok </u></h1>
			<p>Az Átlátszónet Alapítvány többféle képzést tart, egyrészt civil szervezeteknek, közösségeknek, aktív állampolgároknak és egyetemista vagy már gyakorló újságíróknak, másrészt pedig a középiskolás korosztálynak. Jelenleg 5 féle témában tartunk képzést:</p>
			<ul>
			<li>Információszabadság, közérdekűadat-igénylés</li>
			<li>Médiaszabadság, oknyomozó újságírás</li>
			<li>Adatvizualizáció</li>
			<li>Álhírek, dezinformáció</li>
			<li>Adatvédelem, adatbiztonság</li>
			</ul>
			<h3></h3>
			<h3><strong>Közérdekűadat-igénylés workshop</strong></h3>
			<p>Félnapos workshopunk az információszabadságról szóló törvény rövid ismertetésével kezdődik, majd nemzetközi példákat hoz olyan online eszközökre, amelyek az állampolgárokat a közérdekű-adatigénylések beadásában segítik. Az előadás során a résztvevők megismerik a közérdekű adat fogalmát és az atlatszo.hu nyilvános közérdekűadat-igénylő platformját, a KiMitTud-ot. A jogászcsapat egyik tagja betekintést nyújt a közérdekűadat-igénylés jogi hátterébe: elmondja, hogy mely adat tartozik a közérdekű adatok körébe, milyen lépéseket tehetünk, ha igénylésünket elutasítják, és felsorolja azokat a hatóságokat és NGO-kat, melyek jogi segítséget nyújtanak, amennyiben jogi lépések megtételére kényszerülünk. A résztvevők ezt követően gyakorlati segítséget kapnak egy közérdekűadat-igénylés beadásához: regisztrálnak a KiMitTud felületén, és egy munkatársunk segítségével kiválasztják a megfelelő adatgazdát, megszövegezik az igénylést úgy, hogy a kívánt információhoz jussanak, majd elküldik azt. A képzés végére a résztvevők megszerzik a közérdekűadat-igényléshez szükséges alapvető a ismereteket: képesek lesznek a megfelelő adatgazda kiválasztására, az igénylés megszövegezésére, valamint &#8211; az adatigénylések megakadása esetén &#8211; a megfelelő jogi lépések megtételére.</p>
			<p>A <strong>középiskolás korosztálynak</strong> erre a témára egy 45 perces tananyagot dolgoztunk ki, mely <strong><a title="Közérdekű adatigénylés" href="http://veddkiareszed.hu/portfolio-posts/kozerdeku-adatigenyles/" target="_blank">itt érhető el</a></strong>. Az interaktív foglalkozáson a diákok az atlatszo.hu újságíróinak vezetésével az elméleti ismeretek elsajátítása mellett kis csoportokban dolgozzák fel az állampolgári részvétel, a közérdek, és a közérdekű adat témáját.</p>
			<h3><strong>Oknyomozó újságírás workshop</strong></h3>
			<p>Workshopunk témája az oknyomozó újságírás alapjai, melyet az atlatszo.hu oknyomozó újságírói tartanak, alapvető ismereteket nyújtva az oknyomozó újságírásról, valamint arról, hogyan írjunk közérdekű adatokon alapuló cikket, blogposztot. Munkatársaink kifejtik a hiteles blogposztok írása során követendő módszertant, lépésről-lépésre bemutatva az információ megszerzésétől a poszt megírásáig terjedő folyamatot, miközben saját munkájukból hoznak példákat. A résztvevők megismerik a &#8220;fact-checking&#8221; fontosságát, hasznos interjú technikákat tanulnak, a nyilvános adatbázisok (pl. cégadatbázisok, közbeszerzési adatbázisok, stb.)  használatához, valamint a helyi források megtalálásához kapnak hasznos segítséget, és általánosságban megtanulják a hagyományos print források (pl. helyi újságok, könyvtárak, levéltárak) használatát. Arról is konkrét információt kapnak, hogyan tervezzenek meg egy oknyomozó sztorit a projekt elejétől a végéig. A képzésvezetők kiemelik, hogy a források megvédése különös fontossággal bír, és beszélnek arról is, hogyan kerüljük el a sajtópereket (a megjelenés előtt mindig kérjünk &#8220;legal check&#8221;-et). A workshop végére a résztvevők képesek lesznek a nyilvános adatbázisok használatára, megtanulják hogyan találják meg és hasznosítsák a helyi forrásokat, hasznos interjú technikákat ismernek meg, alapvető ismereteket szereznek a médiajog terén, valamint megtanulják hogyan tervezzék meg oknyomozó munkájukat az adatok gyűjtésétől a poszt megírásáig és publikálásáig. A résztvevő bloggerek és újságírók alapvető újságíró és szerkesztő technikák birtokába jutnak &#8211; hogyan rendszerezzék a megszerzett információt és hogyan mondják a történetet úgy, hogy az hiteles, mégis emészthető legyen a széles olvasóközönség számára.</p>
			<p>A független média és az oknyomozó újságírás témájának feldolgozására a <strong>középiskolás korosztály</strong> számára külön tananyagot fejlesztettünk. A 90 perces foglalkozás során egy konkrét esettanulmányon keresztül játékos formában sajátíthatják el az oknyomozó újságírás alapjait. A tananyag <strong><a title="Oknyomozó újságírás" href="http://veddkiareszed.hu/portfolio-posts/mediaszabadsag/" target="_blank">itt érhető el</a></strong>.</p>
			<h3><strong>Adatvizualizáció workshop</strong></h3>
			<p>Az atlatszo.hu újságírói rendszeresen használnak olyan kész (off-the-shelf) adatvizualizációs eszközöket (infogr.am, VIS), melyek komplex cég- és bűnügyi hálózatok feltérképezésében nyújt segítséget az oknyomozó újságírónak. Az adatvizualizáció használatával célunk, hogy segítsük az olvasókat a korrupció, a szervezett bűnözés, és egyéb törvénytelenségek megértéséhez, továbbá az, hogy a komplex írott történeteket egyszerű vizuális nyelvre fordítsuk. Egynapos workshopunk során a résztvevők megtanulják, hogy mi az adat, milyen adatokat és formátumokat használnak az adatújságírók, és ezeket hol találják meg; milyen jellegű elméleti és gyakorlati problémák merülhetnek fel az adatkezelés során, és mi a jó adatdesign. A workshop második felében a résztvevők gyakorlati tapasztalatot szereznek az adatújságírásban és adatvizualizációban használatos legújabb eszközökkel: PDFTables, Tabula, és Import.io felhasználásával gyakorolják az adatkonvertálást, egyszerű trükköket sajátítanak el Excelben, egyszerű adatokat jelenítenek meg Infogramban és összetettebb adatokat Tableau-ban, majd térkép-vizualizációt tanulnak Carto és Tableau felhasználával. A workshop végére a résztvevő újságírók megtanulják, honnan, milyen formában tudnak kis és nagy mennyiségű adatot beszerezni, hogyan tudják az adatokat felhasználhatóvá tenni, és hogyan tudnak az adatokból grafikonokat, összetettebb vizualizációkat, térképeket készíteni.</p>
			<p><strong>Általános és középiskolások</strong>nak szóló fél napos <strong><a title="Programozzunk együtt" href="https://atlatszonet.hu/2017/12/18/programozzunk-egyutt/" target="_blank">workshopunk</a></strong> során játékos formában ismerkedhetnek a diákok az adatokkal, az adatvizualizáció alapjaival és az adatvizualizáció, mint eszköz használatával. Fontosnak tartjuk, hogy ne csak használják az eszközöket, hanem értsék is azok működését, ezzel segítve őket új összefüggések és értelmezések megtalálásában.</p>
			<h3><strong>Álhírvadász workshop</strong></h3>
			<p>Az Atlatszo.hu 2017-ben indította el a <strong>középiskolás diákok</strong>at célzó online kvízt, a &#8220;Legyél te is álhírvadász!&#8221; játékot (<a title="Álhírvadász" href="http://alhirvadasz.hu/" target="_blank">http://alhirvadasz.hu/</a>), amelyhez az online eszköz használatáról szóló, tanárok számára kidolgozott workshop is tartozik. A &#8220;Legyél te is álhírvadász!&#8221; egy online teszt, amely játékos formában szeretné megtanítani a használóit arra, hogyan lehet felismerni az álhíreket, dezinformációkat, a szenzáció mögötti túlzásokat, illetve az összeesküvés-elméleteket. A játékhoz kapcsolódóan a folyamatosan bővülő weboldalon hasznos fogalmakat, olvasmányokat és egyéb eszközöket talál a felhasználó. A diákok négy szinten játszhatnak, a teljesített szinteket pedig megoszthatják Facebook-on és Twitter-en is, amely a kvízt vonzóvá teszi a fiatal felhasználók számára. Az online eszköz rövid magyarázatokkal segíti a játékost a teszt során. A tanárok számára készülő workshop jelenleg fejlesztés alatt áll, mert hosszú távon szeretnénk elérni, hogy az iskolákban önállóan is alkalmazható legyen az eszköz. Eközben az atlatszo.hu újságírói elviszik az Álhírvadászt az iskolákba, ahol 45 perces társadalomismeret, vagy média óra keretében bemutatják a diákoknak. A rendhagyó órák alatt a diákok megismerkednek az &#8220;álhír&#8221; fogalmával, az álhírterjesztők trükkjeivel, továbbá megtanulják, hogyan ismerjék fel a szenzáció mögötti túlzásokat. A feladatok teljesítéséhez a diákok saját okostelefonjukat használják. Ingyenes workshopjainkat a 10-14 és 14-18 éves korosztálynak ajánljuk.</p>
			<h3><strong>Adatvédelem, biztonság workshop</strong></h3>
			<p>Félnapos workshopunk célja, hogy felhívjuk az újságírók és aktivisták figyelmét az informatikai biztonságot veszélyeztető kockázatokra. Esettanulmányokon keresztül a résztvevők olyan témákkal ismerkednek, mint a lehallgatás, PC monitorozás, e-mail hackelés, támadások a közösségi médián keresztül, digitális eszközök lefoglalása vagy ellopása, telefonos vagy online verbális fenyegetések, és a kibertámadás különböző változatai. A workshop végére az újságírók hasznos eszközöket kapnak a kezükbe, melyekkel minimalizálhatják a kiberbiztonságuk megsértésének kockázatát. A résztvevők megismerkednek a végpont védelemmel (endpoint protection), jó jelszó általi online azonosító védelem (account protection via good passwords) és két-lépcsős hitelesítés (two-factor authentication), a tárolt adatok titkosításával (the encryption of locally-stored data) valamint az operációs rendszerekbe épített titkosítási eszközöket használó alkalmazásokkal, és a biztonságos adatátvitel lehetőségeivel (protection of data in transit).</p>
			<p>&nbsp;</p>
			<p>A diákoknak szóló workshopokat rendhagyó iskolai események alkalmával, pl. “Demokrácia Nap”, “Témahét” keretében vagy osztályfőnöki, társadalomismeret, esetleg fakultációs foglalkozások keretében ajánljuk megtartásra.</p>
			<p>Civil szervezetek, közösségek, egyetemista vagy már gyakorló újságíróknak szóló workshopjainkat pedig kihelyezett workshop vagy valamilyen esemény (összejövetel, megbeszélés, képzés, tábor stb.) keretében ajánljuk.</p>
			<p>Akit érdekel ez a lehetőség, jelezze nekünk emailben, hogy a további részleteket egyeztetni tudjuk. Kapcsolat: <a href="mailto:workshop@atlatszo.hu"><strong>workshop@atlatszo.hu</strong></a></p>
			<p>A 2018-as évben a Magnetbank KAP projektje keretén belül a képzések az Átlátszóval közösen zajlanak.</p>
			<p>&nbsp;</p>
		</div>
		<!--Jobb rész, RSS-->
		<div class="col-sm-4 right">
			<h2>#Azenadombol</h2>
			<img class="img-responsive" src="./images/kormanypropaganda_300.gif" alt="Kormány propaganda" />
			<h2 class="widget-title"><a class="rsswidget" href="http://atlatszo.hu/feed"><img class="rss-widget-icon" style="border:0" width="14" height="14"  src="https://atlatszonet.hu/wp-includes/images/rss.png" alt="RSS" /></a> <a class="rsswidget" href="https://atlatszo.hu/">atlatszo.hu</a></h2>
			<ul class="rss"><li><a class='rsswidget' href='https://atlatszo.hu/2019/03/04/tiszakecsketol-bulgarian-at-dubajig-igy-lett-szijj-laszlo-a-ner-egyik-legfontosabb-uzletembere/'>Tiszakécskétől Bulgárián át Dubajig: így lett Szíjj László a NER egyik legfontosabb üzletembere</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/03/02/ki-nem-fel-a-farkastol-a-romaniai-korrupcioellenes-harc-sztarja-lehet-az-europai-fougyesz/'>Ki nem fél a farkastól? A romániai korrupcióellenes harc sztárja lehet az európai főügyész</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/03/01/fuggoseg-bantalmazas-es-lerombolt-onbecsules-ket-no-utja-a-hajlektalansag-szelere-es-vissza/'>Függőség, bántalmazás és lerombolt önbecsülés – két nő útja a hajléktalanság szélére, és vissza</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/27/helyi-civilek-tiltakoznak-epuletet-is-csak-nehezen-sikerult-talalni-a-kozigazgatasi-fobirosagnak/'>Helyi civilek tiltakoznak, épületet is csak nehezen sikerült találni a közigazgatási főbíróságnak</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/26/olaf-jelzesek-hatszorosan-tulszamlaztak-a-szegedi-vadaspark-jatszoteret-es-latogato-tajekoztato-rendszeret/'>OLAF-jelzések: hatszorosan túlszámlázták a szegedi vadaspark játszóterét és látogató-tájékoztató rendszerét</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/18/triciumszivargas-es-nejlonba-csomagolt-hulladek-kerdesek-a-puspokszilagyi-atomtemeto-korul/'>Tríciumszivárgás és nejlonba csomagolt hulladék: kérdések a püspökszilágyi atomtemető körül</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/14/olaf-jelzesek-ot-eve-nyomoz-a-nav-az-14-milliardos-jatszoter-botranyban/'>OLAF-jelzések: öt éve nyomoz a NAV az 1,4 milliárdos játszótér-botrányban</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/11/helyreigazitasi-perek-indulhatnak-az-mti-orszagos-sajtoszolgalata-ellen-a-kuria-dontese-nyoman/'>Helyreigazítási perek indulhatnak az MTI Országos Sajtószolgálata ellen a Kúria döntése nyomán</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/08/foci-templom-iskola-84-milliard-forint-allami-tamogatas-ment-tavaly-a-hataron-tulra/'>Foci, templom, iskola: 84 milliárd forint állami támogatás ment tavaly a határon túlra</a></li><li><a class='rsswidget' href='https://atlatszo.hu/2019/02/07/109-helyreigazitasi-pert-vesztett-2018-ban-a-kormanykozeli-media/'>109 helyreigazítási pert vesztett 2018-ban a kormányközeli média</a></li></ul>
		</div>
	</div>
</div>